### ISSUE TITLE
Ignore broken topics

### ISSUE THREAD

**Issue by mariussoutier** [ldaniels528/trifecta#14]
Hi,

trifecta finds my Kafka brokers without a problem, but it can't find the topics or consumers. 

I can only see this error in the console:
`Resource '/rest/getTopicSummaries' failed unexpectedly WARNING arguments left: 1`

(Btw. the arguments left part means the Akka logging was used in the wrong order.).

**Comment by mariussoutier** [comment]
I just tried with an older version of Trifecta and can see the following error:

`com.ldaniels528.trifecta.io.kafka.KafkaMicroConsumer$VxKafkaCodeException: Leader Not Available`

But it is not clear which topic is causing the problem. Because those who are actively used also have a leader.

**Comment by ldaniels528** [comment]
What can you tell me about your configuration?

On Thu, Nov 26, 2015 at 9:29 AM, Marius Soutier <notifications@github.com>
wrote:

> I just tried with an older version of Trifecta and can see the following
> error:
>
> com.ldaniels528.trifecta.io.kafka.KafkaMicroConsumer$VxKafkaCodeException:
> Leader Not Available
>
> But it is not clear which topic is causing the problem. Because those who
> are actively used also have a leader.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ldaniels528/trifecta/issues/14#issuecomment-159964094>
> .
>



-- 
Best Regards,

Lawrence Daniels

**Comment by mariussoutier** [comment]
What do you need to know? I just entered the three ZooKeepers and they are recognized correctly. The three brokers are recognized as well. One of the topics must be broken, but Trifecta should not fail completely, it should ignore broken topics.

**Comment by mariussoutier** [comment]
The PR fixes the problem...
