### ISSUE TITLE
High CPU cost and High Network TIME_WAIT in 0.18.20

### ISSUE THREAD

**Issue by yiming187** [ldaniels528/trifecta#19]
Hi Daniels,

I'm trying the new version 0.18.20, trifecta_ui. But I found very high CPU cost and high network TIME_WAIT. I have 70+ topics. In the last version, the CPU load is less than 1, but the new version will reach to 4. And the TIME_WAIT reach 15,000 from 30. Is there any configuration I should update when upgrading?

**Comment by ldaniels528** [comment]
Try using the latest version (0.19.0). No configuration properties need to change when migrating.
