### ISSUE TITLE
Can't see consumers

### ISSUE THREAD

**Issue by gzoller** [ldaniels528/trifecta#22]
This may well be pilot error on my part...

I start my kafka server (0.9.0.1) then trifecta cli (I built but couldn't run the web client--Publishing these trifecta flavors in a Docker image would be very cool! :-))

I run some tests that create, write to, and read from a topic.

In trifecta I do this:

kbrokers -- I can see my broker w/jmx port
kls -- I can see two topics: mine (lowercaseStrings), plus __consumer_offsets
kstats lowercaseStrings -- I see 4 partitions I expect with reasonable/expected values for offsets

but if I do:

kconsumers -- I get 'No data returned'

How can I see my consumers?  I'd like to know if where my consumers' offsets are set.
I did add this to my config file in ~/.trifecta:  trifecta.storm.kafka.consumers.partitionManager = false

**Comment by gzoller** [comment]
I forgot to add--this is Trifecta 0.19.2
Latest build from master on github at the time of this writing.

**Comment by ldaniels528** [comment]
How were your consumer offsets created? In other words, are you using Storm
and it created them or were they created by some Kafka client?

On Wed, Apr 6, 2016 at 7:57 AM, Greg Zoller <notifications@github.com>
wrote:

> I forgot to add--this is Trifecta 0.19.2
> Latest build from master on github at the time of this writing.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ldaniels528/trifecta/issues/22#issuecomment-206415554>
>



-- 
Best Regards,

Lawrence Daniels

**Comment by gzoller** [comment]
I'm just using a KafkaConsumer object in Java.  No Storm to my knowledge.

**Comment by ldaniels528** [comment]
The latest release fixes this issue. There are 3 types of Kafka consumers:
1) New built-in consumer 0.9.x
2) Zookeeper-based consumers 0.8.x
3) Storm Partition Manager consumers

Trifecta now supports all 3.
