### ISSUE TITLE
cli doesn't reset the terminal properly on exit

### ISSUE THREAD

**Issue by gzoller** [ldaniels528/trifecta#23]
I'm using iTerm on a Mac.

When I enter 'exit' in the cli to return to bash the terminal is left in a funky state--specifically characters I type aren't displayed on the screen.

The term library you're using probably has some kind of reset feature for this.

**Comment by ldaniels528** [comment]
I'll look into this.

**Comment by ldaniels528** [comment]
Yes this is indeed a bug with Jline, the library I'm using for the REPL  (only affects Mac OS X). For now, just enter "reset" in the terminal and it will fix/reset the terminal. Hopefully this issue will be fixed soon.

http://stackoverflow.com/questions/9557277/how-to-fix-terminal-when-scala-interpreter-causes-invisible-text
