### ISSUE TITLE
Topic message counts off by 1 per partition

### ISSUE THREAD

**Issue by mikesparr** [ldaniels528/trifecta#27]
I view a 9-partition topic in Trifecta and it says I have 91 messages. I consume those messages and publish to another database. I query the sink (other database) and it has 100 records. It appears your counts in Trifecta are off by 1 message per partition in the offsets and message counts. `v0.21` (latest)

This is evident as well when checking that issue #26 you'll see your offset counts are 1 record different than the CLI tool from Kafka's counts when I compared the consumer offsets.

**Comment by ldaniels528** [comment]
Fixed.
