### ISSUE TITLE
Unable to see Query and publish tabs

### ISSUE THREAD

**Issue by sajeevpr** [ldaniels528/trifecta#28]
Hello,
 I started web version 20 and not able to see Query and publish tabs.

Am I doing something wrong.

Regards,
Sajeev

**Comment by ldaniels528** [comment]
Those features were removed

**Comment by mikesparr** [comment]
I was wondering the same thing so glad someone asked. Any particular reason for dropping them @ldaniels528 ?

**Comment by ldaniels528** [comment]
I didn't think those features were really being used. I'll look to re-add them in the next major release.

**Comment by mikesparr** [comment]
Beggars can't be choosers, but it would be nice for non-techies from time to time to be able to publish or look up record for troubleshooting. It's a great tool, thanks!

**Comment by ldaniels528** [comment]
Fixed in the 0.22.x versions
