### ISSUE TITLE
trifecta.web.port setting is not working

### ISSUE THREAD

**Issue by genesis-judy** [ldaniels528/trifecta#32]
I have set the following setting in $HOME/.trifecta/config.properties and restart the process

trifecta.web.host = localhost
trifecta.web.port = 8888

However the web server still listen to 9000?

Thanks!

**Comment by ldaniels528** [comment]
Those options are deprecated. Instead when starting Trifecta UI specify "-Dhttp.port=8888"

For example:
~trifecta_ui/bin/> nohup trifecta_ui -Dhttp.port=8888 &

**Comment by genesis-judy** [comment]
trifecta.kafka.consumers.native = <group_id>    <= Is this option deprecated, too?

the cousmers are not displayed even I have set  trifecta.kafka.consumers.native in $HOME/.trifecta/config.properties

Thanks!

**Comment by ldaniels528** [comment]
No, that's something I need to fix. I'll have a fix within the next couple of days.

**Comment by ldaniels528** [comment]
Try the latest version (0.22.0rc7)

**Comment by ldaniels528** [comment]
Has your issue been resolved?

**Comment by ldaniels528** [comment]
I'm closing this issue. Please re-open it if you have any further issues.
