### ISSUE TITLE
Avro warnings logged for optional fields (using a union type with null)

### ISSUE THREAD

**Issue by miguno** [ldaniels528/trifecta#5]
I think because Trifecta uses Avro 1.7.7 we see many of the following warnings being logged by Trifecta UI.

```
[WARNING] Avro: Invalid default for field foobar: "null" not a ["null","int"]
```

The field `foobar` was defined as follows in the Avro schema:

```json
    {
      "name": "foobar",
      "type": [
        "null",
        "int"
      ],
      "default": "null"
    },
```

I think this may be related to a change in Avro that was introduced in version 1.7.7.  See the discussion at [Passively Converting Null Map To Be Valid](http://qnalist.com/questions/5099781/passively-converting-null-map-to-be-valid) in the avro-user mailing list from August 2014.

Do you know what needs to be changed to fix this warning?

**Comment by vratnagiri-veriskhealth** [comment]
I've had this issue, but one thing I notice is that your default should be: < "default": null > and not < "default": "null" > as can be seen here: http://technicaltidbit.blogspot.com/2013/02/avro-tips.html

Without that, my query was failing. Now that I've fixed that issue, my query runs fine, but I still see the warnings.

**Comment by ldaniels528** [comment]
Thanks for the heads up... but please refresh my memory. Where did I set the default as < "default": null >?

**Comment by vratnagiri-veriskhealth** [comment]
I was referring to this snippet in the original question:

{
      "name": "foobar",
      "type": [
        "null",
        "int"
      ],
      "default": "null"
    },

I should be:
{
      "name": "foobar",
      "type": [
        "null",
        "int"
      ],
      "default": null
    },
