### ISSUE TITLE
Read consumer offset from Kafka directly

### ISSUE THREAD

**Issue by yiming187** [ldaniels528/trifecta#8]
Hi Lawrence,

Currently, trifecta reads consumer offset from zookeeper path /consumers/[group_id]/offsets/[topic]/[broker_id-partition_id]. From 0.8.2, kafka support store offsets in kafka by enabling "offsets.storage=kafka". Does trifecta have the plan to support this feature? 

Thanks.

**Comment by yiming187** [comment]
or we could ignore those topics whose offset does not store in zk. Currently, the KafkaMicroConsumer.getConsumerDetails will throw exception by accessing the non-existing "offsets" path.

**Comment by ldaniels528** [comment]
I'll add support for this new feature by this weekend. Thanks for the heads up!

**Comment by ldaniels528** [comment]
Now that I've finally release v0.19.0, I plan to incorporate the feature you've requested into the next release (v0.19.1)
